apiVersion: apps/v1
kind: Deployment
metadata:
  name: pmc-server-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pmc-server-prod
  template:
    metadata:
      labels:
        app: pmc-server-prod
    spec:
      containers:
      - name: pmc-server-prod
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: us-west1-docker.pkg.dev/pmc-website-bfa1a/pmc-server/pmc-server-prod:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"