FROM golang:1.20-alpine

RUN mkdir /backend
WORKDIR /backend
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o /go/bin/backend

EXPOSE 8080

ENTRYPOINT [ "/go/bin/backend" ]