apiVersion: v1
kind: Service
metadata:
  name: pmc-server-prod
spec:
  type: NodePort
  selector:
    app: pmc-server-prod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
